DROP DATABASE IF EXISTS flask;
CREATE DATABASE flask;
USE flask;
DROP TABLE IF EXISTS plane_crash;
CREATE TABLE `plane_crash` (
  `id` varchar(36) NOT NULL,
  `date` varchar(20) NOT NULL,
  `time` varchar(4) NOT NULL,
  `location` varchar(255) NOT NULL,
  `operator` varchar(255) NOT NULL,
  `flight_number` varchar(50) NOT NULL,
  `route` varchar(255) NOT NULL,
  `ac_type` varchar(255) NOT NULL,
  `registration` varchar(255) NOT NULL,
  `cn_ln` varchar(255) NOT NULL,
  `aboard` varchar(100) NOT NULL,
  `fatalities` varchar(100) NOT NULL,
  `ground` varchar(50) NOT NULL,
  `summary` text NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO plane_crash (
  `id`, 
  `date`, 
  `time`, 
  `location`, 
  `operator`, 
  `flight_number`, 
  `route`, 
  `ac_type`, 
  `registration`, 
  `cn_ln`, 
  `aboard`, 
  `fatalities`, 
  `ground`, 
  `summary`
) 
VALUES
  (uuid(),	'January 20, 2014',	'1634',	'Near Petreasa Romania',	'Scoala Superioara de Aviatie Civla',	'?',	'Bucharest - Oradea',	'Britten Norman BN-2A-27 Islander',	'YR-BNP',	'822',	'7 (passengers:5  crew:2)',	'2 (passengers:1  crew:1)',	'0',	'The air ambulance left Bucharest with a medical team to obtain transplant organs. After experiencing problems with the engines the pilot attempted to make an emergency landing but crashed on a hillside in deep snow. All aboard initially survived but the pilot and a medical student died before the rescue party reached the aircraft.'),
  (uuid(),	'February 11, 2014',	'1159',	'Near Ain Kercha, Algeria',	'Military - Algerian Air Force',	'?',	'Tamanarasset - Constatine',	'Lockheed C-130H-30 Hercules',	'7T-WHM',	'4919',	'77 (passengers:73  crew:4)',	'76 (passengers:72  crew:4)',	'0',	'The military transport crashed into a mountainous region approximaely 30 miles southeast of Constatine Airport. Unfavorable weather conditions and storms accompanied by snow were reported in the area. The aircraft was too low on approach and hit the slope of mount Djebel Ta Fertas.'),
  (uuid(),	'February 16, 2014',	'1315',	'Sandhikhark, Nepal',	'Nepal Airlines',	'183',	'Kathmandu - Pokhara - Jumla',	'de Havilland Canada DHC-6 Twin Otter 300',	'9N-ABB',	'302',	'18 (passengers:15  crew:3)',	'18 (passengers:15  crew:3)',	'0',	'The passenger plane crashed into a snow covered mountain and burst into flames while en route from Pokhara to Jamia. Weather was poor at the time of the accident. The PIC lost situation awareness while cruising in IMC, causing the aircraft to collide with terrain'),
  (uuid(),	'February 21, 2014',	'0145',	'Grombalia, Tunisia',	'Libyan Air Cargo',	'?',	'Tripoli - Tunis',	'Antonov 26',	'	5A-DOW',	'11809',	'11 (passengers:6  crew:5)',	'11 (passengers:6  crew:5)',	'0',	'The aircraft, carrying a medical team with three patients, was destroyed when it crashed in a field, 20 miles from Tunis-Carthage Airport. The pilot reported an engine on fire prior to the accident.'),
  (uuid(),	'March 08, 2014',	'0241',	'South Indian Ocean',	'Malaysia Airlines',	'370',	'Kuala Lumpur - Beijing',	'Boeing 777-200',	'9M-MRO',	'28420/404',	'239 (passengers:227  crew:12)',	'239 (passengers:227  crew:12)',	'0',	'Radar contact was lost with the aircraft 2 hours into the flight at 0240. All indications are that the aircraft changed direction from its flight path and crashed in a remote part of the Indian Ocean southwest of Perth Australia. It is assumed all 227 passengers and crew of 12 perished. The cause remains unknown.'),
  (uuid(),	'March 18, 2014',	'0752',	'Seattle, Washington',	'Helicopters Inc / KOMO TV',	'?',	'News reporting',	'Urocopter AS350 B2',	'N250FB',	'3669',	'2 (passengers:1  crew:1)',	'2 (passengers:1  crew:1)',	'0',	'The news helicopter crashed and burst into flames shortl after taking off striking three vehicles. One person in one of the vehicles was badly burned. The helicopter Photojournalist Bill Strothman and the pilot were both killed.'),
  (uuid(),	'April 19, 2014',	'1945',	'Ramos Arizpe, Mexico',	'Lineas Aereas Comerciales',	'?',	'Cozumel - Ramos Arizpe',	'British Aerospace BAe 125-700A Hawker',	'XA-UKR',	'25719',	'8 (passengers:6  crew:2)',	'	8 (passengers:6  crew:2)',	'0',	'While on approach, in fog, the jet crashed into an park about half-a-mile north of Saltillo-Plan de Guadalupe International Airport.'),
  (uuid(),	'April 20, 2014',	'1530',	'Jamijarvi, Finland',	'Suomen Urheiluilmailijat',	'?',	'Skydiving',	'Aerocomp Comp Air 8',	'OH-XDZ',	'?',	'8 (passengers:7  crew:1)',	'8 (passengers:7  crew:1)',	'0',	'While carrying skydivers, the experimental plane went into a spin and crashed and burned in a forest. The pilot and two skydivers were able to parachute to safety with minor injuries.'),
  (uuid(),	'May 08, 2014',	'1245',	'Near San Vicente del Caguan, Colombia',	'Alisansa Colombia',	'?',	'Villavicencio - Florencia',	'Douglas DC-3C',	'HK-4700',	'9700',	'6 (passengers:0  crew:6)',	'6 (passengers:0  crew:6)',	'0',	'The Cargo plane sruck the side of a mountain about 25 miles north of San Vicente del Caguán while en route. The accident was the result of a controlled flight into terrain. The crew failed to evaluate properly the risks and the danger of poor weather conditions and decided to perform the flight in VFR mode.'),
  (uuid(),	'May 17, 2014',	'0800',	'Xiang Khouang province, Laos',	'Laos Air Force',	'?',	'Vientiane - Xiangkhoung',	'Antonov 74TK-300',	'RDPL-34020',	'36547098982',	'17 (passengers:11  crew:6)',	'16 (passengers:10  crew:6)',	'0',	'The military aircraft crashed in a wooded area while approaching Xiangkhoungs airport, killing 16 people. Among those killed were defense minister Douangchay Phichit and other high ranking officials. For unknown reason, crew was approaching at a too low an altitude.'),
  (uuid(),	'June 14, 2014',	'0050',	'Lugansk, Ukraine',	'Military - Ukraine Air Force',	'?',	'Melitopol - Luhansk',	'Ilyushin 76MD',	'76777',	'0083482490',	'49 (passengers:40  crew:9)',	'	49 (passengers:40  crew:9)',	'0',	'	The military transport crashed in a wheat field near Lugansk Airport after being shot down by anti-aircraft fire'),
  (uuid(),	'July 02, 2014',	'?',	'Near Nairobi, Kenya',	'Skyward International Aviation',	'?',	'Nairobi - Mogadishu, Somalia',	'Fokker 50',	'5Y-CET',	'20262',	'4 (passengers:0  crew:4)',	'4 (passengers:0  crew:4)',	'0',	'The cargo plane, transporting the mild stimulant known as Khat to the Somali capital, Mogadishu, crashed into a commercial building after taking off from Jomo Kenyatta International Airport. While climbing by night, crew lost control of the aircraft. The probable cause of the accident was the decision by the crew to conduct the flight with a known mechanical problem and their failure to abort or reject the takeoff after receiving twenty-seven cautions.'),
  (uuid(),	'July 07, 2014',	'0750',	'Thach That district, Vietnam',	'Military - Vietnam Peoples Army Air Force',	'?',	'Training',	'Mil Mi-171',	'?',	'?',	'19 (passengers:21  crew:2)',	'18 (passengers:?  crew:?)',	'0',	'The helicopter crashed about 40 km west of Hanoi, 15 minutes after taking off during a parachute training mission.'),
  (uuid(),	'July 17, 2014',	'1619',	'Hrabove, Ukraine',	'Malaysia Airlines',	'17',	'Amsterdam - Kuala Lumpur',	'Boeing 777-2H6ER',	'9M-MRD',	'28411/84',	'298 (passengers:283  crew:15)',	'298 (passengers:283  crew:15)',	'0',	'A Boeing 777-200 airliner operating as Malaysia Airlines Flight 17, crashed about 40 miles east of Donetsk, Ukraine. The plane was 90 minutes into its flight, flying at 33,000 feet, when it was apparently hit by a Russian Buk missile. The missile exploded a few feet away from the cockpit .Debris was spread over a wide area. All 283 passengers and crew of 15 were killed.'),
  (uuid(),	'July 23, 2014',	'1906',	'Magong, Taiwan',	'TransAsia Airways',	'222',	'Kaohsiung - Magong',	'ATR 72-500',	'B-22810',	'642',	'58 (passengers:54  crew:4)',	'48 (passengers:44  crew:4)',	'0',	'The passenger plane crashed into residential building while attempting to make an emergency landing during inclement weather due to the passing of hurricane Matmo. The flight recorder revealed that after the the crew lost track of its flight path and moved away from the runway, the plane rapidly lost altitude and crashed to the ground in a period of 7.9 seconds. By the time the two pilots yelled to go around, there was nothing they could do to change the velocity and altitude of the plane in time to prevent a crash. The airports control tower did not inform the aircraft of local weather conditions.The cause was pilot error and a failure within the airline to follow safety procedures. The flight crew did not comply with the published runway 20 VOR non-precision instrument approach procedures at Magong Airport with respect to the minimum descent altitude. The captain, as the pilot flying, intentionally descended the aircraft below the published MDA of 330 feet in the instrument meteorological conditions'),
  (uuid(),	'July 24, 2014',	'0147',	'Aguelhok, Mali',	'Air Algerie',	'AH5017',	'Ouagadougou, Burkina Faso - Algiers, Algeria',	'Mc Donnell Douglas MD-83',	'EC-LTV',	'53190/2148',	'116 (passengers:110  crew:6)',	'116 (passengers:110  crew:6)',	'0',	'	Radar contact was lost 50 minutes after the flight took off from Ouagadougou and after the crew diverted from their planned course due to bad weather. Wreckage was found in the northern mali dessert. The plane was on loan from Swiftair. The crew likely did not activate the system during climb and cruise. As a result of the icing of the pressure sensors, the erroneous information transmitted to the auto throttle meant that the latter limited the thrust delivered by the engines. Under these conditions, the thrust was insufficient to maintain cruise speed and the aircraft slowed down and stalled.'),
  (uuid(),	'August 10, 2014',	'0918',	'Tehran, Iran',	'Sepahan Airlines',	'5915',	'Tehran - Tabas',	'HESA Iran-140-100',	'EP-GPA',	'9005',	'48 (passengers:40  crew:8)',	'39 (passengers:31  crew:8)',	'0',	'	After taking off, the passenger banked to the right, lost altitude, and crashed into a residential neighborhood, bursting into flames. The plane appeared to have lost an engine during the takeoff. Excessive load and malfuncioning propeller.'),
  (uuid(),	'August 30, 2014',	'0244',	'Tamanraset, Algeria',	'Ukraine Air Alliance',	'?',	'Glascow -Tamanraset - Equitorial Guinea',	'Antonov An-12BK',	'UR-DWF',	'8345802',	'7 (passengers:5  crew:2)',	'7 (passengers:5  crew:2)',	'0',	'The cargo plane crashed in the mountainous southeastern region of Algereia, 15 km south of the airport, shortly after taking off.'),
  (uuid(),	'August 31, 2014',	'1945',	'Mwanza, Tanzania',	'Safari Express Cargo',	'?',	'Mwanza - Nairobi',	'Fokker F-27 MK 500',	'5Y-SXP',	'10681',	'3 (passengers:1  crew:2)',	'3 (passengers:1  crew:2)',	'0',	'The cargo plane crashed within the borders of Serengeti National Park not far from the Kenya - Tanzania border, shortly after taking off from Mwanza.'),
  (uuid(),	'September 20, 2014',	'0935',	'Near Port Moresby, Papua New Guinea',	'Hevlift',	'?',	'Woitape - Port Moresby',	'de Havilland Canada DHC-6 Twin Otter 300',	'P2-KSV',	'528',	'9 (passengers:7  crew:2)',	'4 (passengers:2  crew:2)',	'0',	'While approaching Port Moresby Jacksons International Airport, the unscheduled passenger plane impacted terrain near the top of Mt. Lawes, 7 miles east northeast of the airport in poor weather. The crew continued the descent in instrument meteorological conditions without confirming their position. The flight crew’s assessment of their position was incorrect and they had lost situational awareness.'),
  (uuid(),	'October 04, 2014',	'0156',	'Wichita Falls, Texas',	'Air Evac Lifeteam',	'?',	'Waurika, OK - Wichita Falls, TX',	'Bell 206L',	'?',	'?',	'4 (passengers:1  crew:3)',	'2 (passengers:1  crew:1)',	'0',	'The air ambulance crashed while transporting a patient from Waurika, Oklahoma to United Regional Health Center. The patient was killed and 3 crew members injured.'),
  (uuid(),	'December 28, 2014',	'0300',	'Near Uvira, Congo',	'Air Sirin',	'902',	'Bujumbura, Burundi - Pointe Noire, Congo',	'Antonov An-26',	'4L-AFS',	'8606',	'6 (passengers:0  crew:6)',	'6 (passengers:0  crew:6)',	'0',	'The cargo plane impacted a mountainside while en route.'),
  (uuid(),	'December 28, 2014',	'0618',	'Java Sea',	'AirAsia',	'8501',	'Surabaya - Singapore',	'Airbus A-320-216',	'PK-AXC',	'3648',	'162 (passengers:155  crew:7)',	'	162 (passengers:155  crew:7)',	'0',	'The aircraft went missing while en route from Suabaya to Singapore. Contact was lost about 40 minutes after taking off. Before contact was lost, the pilot requested a route change due to weather conditions. Preliminary indications are the plane ran into poor weather and stalled from FL320. The rudder travel limiter faulted 3 times during the flight. On the fourth fault the captain decided to try resetting the system by pulling circuit breakers as he had seen a maintenance technician do on the ground. This caused the autopilot to disengage causing the plane to bank 54 degrees. The the first officer, who was flying, became disoriented and was slow to correct the bank. He then put the plane into a steep climb that caused the aircraft to stall and eventually crash. Records show that the plane flew with that mechanical problem for 12 months preceding the accident.');